### ISSUE TITLE
Paginators become unresponsive after some time

### ISSUE THREAD

**Issue by CircuitSacul** [LiBa001/disputils#21]
For some reason, in between adding the reactions and purging the reactions, the paginator becomes completely unresponsive. I honestly don't know what else to say, I've tested on multiple different kinds, but it never happens with my custom paginators.

**Comment by CircuitSacul** [comment]
Alright, it's because messages that aren't cached no longer trigger the `reaction_add` event. Solution would be to use `raw_reaction_add` instead.

**Comment by LiBa001** [comment]
Are you sure the problem is with the cache or could it be the timeout?

**Comment by CircuitSacul** [comment]
I'm positive it's the cache.

**Comment by CircuitSacul** [comment]
reaction_add events only trigger if the message is in the cache. Since the cache is usually limited to 2,000, large bots go through it very quickly and paginators relying on reaction_add become unresponsive very quickly. The solution is, as previously said, to use on_raw_reaction_add instead.

**Comment by LiBa001** [comment]
Alright. I know about the `reaction_add` events only being triggered for cached messages. I just wanted to make sure your specific issue was not caused by the timeout, since this could also cause the pagination to become unresponsive.
Thanks for clarification.

Since I don't know too much about the performance differences between `on_reaction_add` and `on_raw_reaction_add`, would you suggest to make the `raw` mode an option via a parameter or just make it mandatory for everyone.

**Comment by CircuitSacul** [comment]
I would make it madatory. The [RawReactionActionEvent](https://discordpy.readthedocs.io/en/stable/api.html?highlight=rawreactionactionevent#discord.RawReactionActionEvent) will include all the info you need to check if the reaction is valid (user_id, emoji, etc). The emoji attribute will be a PartialEmoji but that just takes some code changes.
